# Run Information
api-version: "1.19"
main: dev.firecontroller.dynmapfow.DynmapFOW
depend: [dynmap]

# Metadata Information
name: ${project.name}
version: ${project.version}
author: FireController#1847
website: https://www.firecontroller.dev/